import React from "react";
import { Container } from "react-bootstrap";

function PrediksiPage() {
    return(
        <div className="prediksi">
            <Container className="py-5">
            <h1>halaman data prediksi</h1>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nobis iure odit iste nesciunt beatae qui dolore dicta exercitationem! Modi, voluptatem perferendis esse consequuntur provident ipsa voluptates, facere eveniet quas explicabo ea et, fuga deleniti omnis reprehenderit? Dolorem obcaecati libero dicta fugiat voluptatum. Vel illo voluptas eius possimus in tenetur doloribus illum quae eum ut qui deleniti exercitationem quisquam, aliquid, neque alias harum fuga expedita explicabo molestias corporis. Nobis vero a, tenetur esse, eaque architecto excepturi ipsum quo debitis consectetur, obcaecati neque fugit tempora labore alias minima maxime quibusdam impedit iure totam! Nulla quasi facere eum quae voluptatem iure maxime nesciunt?</p>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nobis iure odit iste nesciunt beatae qui dolore dicta exercitationem! Modi, voluptatem perferendis esse consequuntur provident ipsa voluptates, facere eveniet quas explicabo ea et, fuga deleniti omnis reprehenderit? Dolorem obcaecati libero dicta fugiat voluptatum. Vel illo voluptas eius possimus in tenetur doloribus illum quae eum ut qui deleniti exercitationem quisquam, aliquid, neque alias harum fuga expedita explicabo molestias corporis. Nobis vero a, tenetur esse, eaque architecto excepturi ipsum quo debitis consectetur, obcaecati neque fugit tempora labore alias minima maxime quibusdam impedit iure totam! Nulla quasi facere eum quae voluptatem iure maxime nesciunt?</p>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nobis iure odit iste nesciunt beatae qui dolore dicta exercitationem! Modi, voluptatem perferendis esse consequuntur provident ipsa voluptates, facere eveniet quas explicabo ea et, fuga deleniti omnis reprehenderit? Dolorem obcaecati libero dicta fugiat voluptatum. Vel illo voluptas eius possimus in tenetur doloribus illum quae eum ut qui deleniti exercitationem quisquam, aliquid, neque alias harum fuga expedita explicabo molestias corporis. Nobis vero a, tenetur esse, eaque architecto excepturi ipsum quo debitis consectetur, obcaecati neque fugit tempora labore alias minima maxime quibusdam impedit iure totam! Nulla quasi facere eum quae voluptatem iure maxime nesciunt?</p>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nobis iure odit iste nesciunt beatae qui dolore dicta exercitationem! Modi, voluptatem perferendis esse consequuntur provident ipsa voluptates, facere eveniet quas explicabo ea et, fuga deleniti omnis reprehenderit? Dolorem obcaecati libero dicta fugiat voluptatum. Vel illo voluptas eius possimus in tenetur doloribus illum quae eum ut qui deleniti exercitationem quisquam, aliquid, neque alias harum fuga expedita explicabo molestias corporis. Nobis vero a, tenetur esse, eaque architecto excepturi ipsum quo debitis consectetur, obcaecati neque fugit tempora labore alias minima maxime quibusdam impedit iure totam! Nulla quasi facere eum quae voluptatem iure maxime nesciunt?</p>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nobis iure odit iste nesciunt beatae qui dolore dicta exercitationem! Modi, voluptatem perferendis esse consequuntur provident ipsa voluptates, facere eveniet quas explicabo ea et, fuga deleniti omnis reprehenderit? Dolorem obcaecati libero dicta fugiat voluptatum. Vel illo voluptas eius possimus in tenetur doloribus illum quae eum ut qui deleniti exercitationem quisquam, aliquid, neque alias harum fuga expedita explicabo molestias corporis. Nobis vero a, tenetur esse, eaque architecto excepturi ipsum quo debitis consectetur, obcaecati neque fugit tempora labore alias minima maxime quibusdam impedit iure totam! Nulla quasi facere eum quae voluptatem iure maxime nesciunt?</p>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nobis iure odit iste nesciunt beatae qui dolore dicta exercitationem! Modi, voluptatem perferendis esse consequuntur provident ipsa voluptates, facere eveniet quas explicabo ea et, fuga deleniti omnis reprehenderit? Dolorem obcaecati libero dicta fugiat voluptatum. Vel illo voluptas eius possimus in tenetur doloribus illum quae eum ut qui deleniti exercitationem quisquam, aliquid, neque alias harum fuga expedita explicabo molestias corporis. Nobis vero a, tenetur esse, eaque architecto excepturi ipsum quo debitis consectetur, obcaecati neque fugit tempora labore alias minima maxime quibusdam impedit iure totam! Nulla quasi facere eum quae voluptatem iure maxime nesciunt?</p>
            </Container>
        </div>
    )
}

export default PrediksiPage; 
